### PR TITLE
Clarify @Incoming method signatures

### LINKED ISSUE #79: Tck SubscriberShapeTest outside of spec
Signature of method [SubscriberBean#consumePayloadsAndReturnSomething](https://github.com/eclipse/microprofile-reactive-messaging/blob/a89bdc57f917827deba171bbea1b067a4aa8c171/tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/subscribers/SubscriberBean.java#L129) is outside of spec defined variants.
```java
    @Incoming("string-payload")
    public String consumePayloadsAndReturnSomething(String payload) {
        increment("string-payload");
        add("string-payload", payload);
        return payload;
    }

```
Spec states:
`Implementations must validate that the stream shape matches the @Outgoing and
@Incoming annotations, if they don’t, a CDI definition exception should be raised to the CDI container
during initialization.`

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #79

* Remove tests using non-supported signatures
* Add new tests in the TCK to be sure these non-supported signatures are detected and reported using CDI Definition Exception
* Clarify the spec about these signatures

### CODE REVIEW

File: tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/invalid/InvalidSubscriberSignatureTest.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+        JavaArchive archive = ShrinkWrap.create(JavaArchive.class)
+            .addClasses(IncomingReturningNonVoidCompletionStage.class, ArchiveExtender.class)
+            .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
+
+        ServiceLoader.load(ArchiveExtender.class).iterator().forEachRemaining(ext -> ext.extend(archive));
+        return archive;
+    }
+
+    @Test
+    public void checkThatIncomingShouldNotReturnNonVoidCompletionStagw() {
```
Comment (xstefank) [inline tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/invalid/InvalidSubscriberSignatureTest.java]:
```suggestion
    public void checkThatIncomingShouldNotReturnNonVoidCompletionStage() {
```

Comment (cescoffier) [reply tck/src/main/java/org/eclipse/microprofile/reactive/messaging/tck/signatures/invalid/InvalidSubscriberSignatureTest.java]: good catch! 
Updated.
